version: '3.8'

services:
    keycloak:
        image: quay.io/keycloak/keycloak:latest
        environment:
            KC_BOOTSTRAP_ADMIN_USERNAME: "admin"
            KC_BOOTSTRAP_ADMIN_PASSWORD: "password"
            KC_HEALTH_ENABLED: "true"

        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:7080/health/ready" ]
            interval: 15s
            timeout: 2s
            retries: 15

        command: [ "start-dev", "--http-port=7080", "--https-port=7443" ]
        ports:
            - "7080:7080"
            - "7443:7443"