### Spring Cloud Gateway Configuration ###
### NO CHANGE THIS FILE ###


eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/


spring:
    application:
        name: api-gateway

    config:
        import: "configserver:"

    cloud:
        config:
            discovery:
                enabled: true
                service-id: config-server


        ### END CLOUD CONFIGURATION ###


        gateway:

            httpclient:
                max-initial-line-length: 16384
                max-header-size: 16384
                max-chunk-size: 10485760 # 10MB, adjust as needed
                response-timeout: 30s

            discovery:
                locator:
                    enabled: true
                    lowerCaseServiceId: true

            routes:
                -   id: chat-service
                    uri: lb://chat-service
                    predicates:
                        - Path=/api/chat/**
                    filters:
                        - RewritePath=/api/chat/(?<path>.*), /$\{path}

                -   id: chat-service-ws
                    uri: lb:ws://chat-service
                    predicates:
                        - Path=/api/messages/**
                    filters:
                        - AddRequestHeader=Authorization, {request.headers.Authorization}
                        - RewritePath=/api/messages/(?<path>.*), /$\{path}


                -   id: post-service
                    uri: lb://post-service
                    predicates:
                        - Path=/api/post/**
                    filters:
                        - RewritePath=/api/post/(?<path>.*), /$\{path}

                -   id: user-service
                    uri: lb://user-service
                    predicates:
                        - Path=/api/user/**
                    filters:
                        - RewritePath=/api/user/(?<path>.*), /$\{path}
            default-filters:
                - TokenRelay=


    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:7080/realms/blog-chat
            client:
                provider:
                    keycloak:
                        issuer-uri: http://localhost:7080/realms/blog-chat
                registration:
                    keycloak:
                        provider: keycloak
                        client-id: backend
                        client-secret: gQCPs3zXyeZWDWAGW5B3fYUuScRKvzYG
                        authorization-grant-type: authorization_code
                        scope: openid, profile, email, roles

### END EUREKA AND CONFIG SERVER CONFIGURATION ###
