spring:
    application:
        name: post-service

    cloud:
        config:
            discovery:
                service-id: config-server
                enabled: true

    config:
        import: "configserver:"
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:7080/realms/blog-chat


eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka

server:
    port: 8081
