spring:
    application:
        name: post-service
    cloud:
        config:
            discovery:
                service-id: config-server
                enabled: true

    config:
        import: "configserver:"


eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka

server:
    port: 8081