spring:
    application:
        name: user-service

    cloud:
        config:
            discovery:
                service-id: config-server
                enabled: true

    config:
        import: "configserver:"

    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:7080/realms/blog-chat




server:
    port: 8083

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka


keycloak:
    url: http://localhost:7080/
    realm: blog-chat
    client-id: backend
    client-secret: gQCPs3zXyeZWDWAGW5B3fYUuScRKvzYG
    password: admin
    username: admin
