spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/blog_chat
        username: spring_admin
        password: password

        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
